services:
  - type: web
    name: betabinary
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: UPESIPAY_BASE_URL
        value: https://api.pesipay.com
